export default{
    Ka: {
      index: 0,
      name: "ka",
      fontpic:require('../../assets/img/letter/1.png'),
      pic:require('../../assets/img/fontCharacters/kaxhuwa.png'),
      uril:require('../../assets/sounds/words/Ka.m4a'),
      isVideo: false,
    },
    Kha: {
      index: 1,
      name: "Kha",
      fontpic:require('../../assets/img/letter/2.png'),
      pic:require('../../assets/img/fontCharacters/kharayo.png'),
      uril:require('../../assets/sounds/words/Kha.m4a'),
      isVideo:false,
    },
    Ga: {
      index: 2,
      name: "Ga",
      fontpic:require('../../assets/img/letter/3.png'),
      pic:require('../../assets/img/fontCharacters/cow.png'),
      uril:require('../../assets/sounds/words/Ga.m4a'),
      isVideo:false,
    },
    Gha: {
      index: 3,
      name: "Ga",
      fontpic:require('../../assets/img/letter/4.png'),
      pic:require('../../assets/img/fontCharacters/house.png'),
      uril:require('../../assets/sounds/words/Gha.m4a'),
      isVideo:false,
    },
    Gnya: {
      index: 4,
      name: "Gnya",
      fontpic:require('../../assets/img/letter/5.png'),
      pic:require('../../assets/img/fontCharacters/cow.png'),
      uril:require('../../assets/sounds/words/Nga.m4a'),
      isVideo:false,
    },
    Cha: {
      index: 5,
      name: "Cha",
      fontpic:require('../../assets/img/letter/6.png'),
      pic:require('../../assets/img/fontCharacters/charan.png'),
      uril:require('../../assets/sounds/words/Cha.m4a'),
      isVideo:false,
    },
    Chha: {
      index: 6,
      name: "Chha",
      fontpic:require('../../assets/img/letter/7.png'),
      pic:require('../../assets/img/fontCharacters/xhata.png'),
      uril:require('../../assets/sounds/words/Chha.m4a'),
      isVideo:false,
    },
    Ja: {
      index: 7,
      name: "Ja",
      fontpic:require('../../assets/img/letter/8.png'),
      pic:require('../../assets/img/fontCharacters/jarayo.png'),
      uril:require('../../assets/sounds/words/Ja.m4a'),
      isVideo:false,
    },
    Jha: {
      index: 8,
      name: "Jha",
      fontpic:require('../../assets/img/letter/8.png'),
      pic:require('../../assets/img/fontCharacters/flag.png'),
      uril:require('../../assets/sounds/words/Jha.m4a'),
      isVideo:false,
    },
    Yna: {
      index: 9,
      name: "Yna",
      fontpic:require('../../assets/img/letter/10.png'),
      pic:require('../../assets/img/fontCharacters/cow.png'),
      uril:require('../../assets/sounds/words/Nga.m4a'),
      isVideo:false,
    },
    Tta: {
      index: 10,
      name: "Ta",
      fontpic:require('../../assets/img/letter/11.png'),
      pic:require('../../assets/img/fontCharacters/taraju.png'),
      uril:require('../../assets/sounds/words/Tta.m4a'),
      isVideo:false,
    },
    Ttha: {
      index: 11,
      name: "Tha",
      fontpic:require('../../assets/img/letter/12.png'),
      pic:require('../../assets/img/fontCharacters/thapadi.png'),
      uril:require('../../assets/sounds/words/Ttha.m4a'),
      isVideo:false,
    },
    Dda: {
      index: 12,
      name: "Da",
      fontpic:require('../../assets/img/letter/13.png'),
      pic:require('../../assets/img/fontCharacters/damaru.png'),
      uril:require('../../assets/sounds/words/Dda.m4a'),
      isVideo:false,
    },
    Ddha: {
      index: 13,
      name: "Dha",
      fontpic:require('../../assets/img/letter/14.png'),
      pic:require('../../assets/img/fontCharacters/dhakan.png'),
      uril:require('../../assets/sounds/words/Ddha.m4a'),
      isVideo:false,
    },
    Yana: {
      index: 14,
      name: "Yana",
      fontpic:require('../../assets/img/letter/15.png'),
      pic:require('../../assets/img/fontCharacters/cow.png'),
      uril:require('../../assets/sounds/words/Nna.m4a'),
      isVideo:false,
    },
    Tah: {
      index: 15,
      name: "Tah",
      fontpic:require('../../assets/img/letter/16.png'),
      pic:require('../../assets/img/fontCharacters/taraju.png'),
      uril:require('../../assets/sounds/words/Tah.m4a'),
      isVideo:false,
    },
    Tha: {
      index: 16,
      name: "Tha",
      fontpic:require('../../assets/img/letter/17.png'),
      pic:require('../../assets/img/fontCharacters/thapadi.png'),
      uril:require('../../assets/sounds/words/Tha.m4a'),
      isVideo:false,
    },
    Daa: {
      index: 17,
      name: "Daa",
      fontpic:require('../../assets/img/letter/18.png'),
      pic:require('../../assets/img/fontCharacters/daraj.png'),
      uril:require('../../assets/sounds/words/Daa.m4a'),
      isVideo:false,
    },
    Dhaa: {
      index: 18,
      name: "Dhaa",
      fontpic:require('../../assets/img/letter/19.png'),
      pic:require('../../assets/img/fontCharacters/dharharra.png'),
      uril:require('../../assets/sounds/words/Dhaa.m4a'),
      isVideo:false,
    },
    Na: {
      index: 19,
      name: "Na",
      fontpic:require('../../assets/img/letter/20.png'),
      pic:require('../../assets/img/fontCharacters/cow.png'),
      uril:require('../../assets/sounds/words/Na.m4a'),
      isVideo:false,
    },
    Pa: {
      index: 20,
      name: "Pa",
      fontpic:require('../../assets/img/letter/21.png'),
      pic:require('../../assets/img/fontCharacters/pareywa.png'),
      uril:require('../../assets/sounds/words/Pa.m4a'),
      isVideo:false,
    },
    Pha: {
      index: 21,
      name: "Pha",
      fontpic:require('../../assets/img/letter/22.png'),
      pic:require('../../assets/img/fontCharacters/fruits.png'),
      uril:require('../../assets/sounds/words/Pha.m4a'),
      isVideo:false,
    },
    Ba: {
      index: 22,
      name: "Ba",
      fontpic:require('../../assets/img/letter/23.png'),
      pic:require('../../assets/img/fontCharacters/basuri.png'),
      uril:require('../../assets/sounds/words/Ba.m4a'),
      isVideo:false,
    },
    Bha: {
      index: 23,
      name: "Bha",
      fontpic:require('../../assets/img/letter/24.png'),
      pic:require('../../assets/img/fontCharacters/vakundo.png'),
      uril:require('../../assets/sounds/words/Bha.m4a'),
      isVideo:false,
    },
    Ma: {
      index: 24,
      name: "Ma",
      fontpic:require('../../assets/img/letter/25.png'),
      pic:require('../../assets/img/fontCharacters/makai.png'),
      uril:require('../../assets/sounds/words/Ma.m4a'),
      isVideo:false,
    },
    Ya: {
      index: 25,
      name: "Ya",
      fontpic:require('../../assets/img/letter/26.png'),
      pic:require('../../assets/img/fontCharacters/yamari.png'),
      uril:require('../../assets/sounds/words/Ya.m4a'),
      isVideo:false,
    },
    Ra: {
      index: 26,
      name: "Ra",
      fontpic:require('../../assets/img/letter/27.png'),
      pic:require('../../assets/img/fontCharacters/rath.png'),
      uril:require('../../assets/sounds/words/Ra.m4a'),
      isVideo:false,
    },
    La: {
      index: 27,
      name: "La",
      fontpic:require('../../assets/img/letter/28.png'),
      pic:require('../../assets/img/fontCharacters/lasun.png'),
      uril:require('../../assets/sounds/words/La.m4a'),
      isVideo:false,
    },
    Wa: {
      index: 28,
      name: "Wa",
      fontpic:require('../../assets/img/letter/29.png'),
      pic:require('../../assets/img/fontCharacters/wakil.png'),
      uril:require('../../assets/sounds/words/Wa.m4a'),
      isVideo:false,
    },
    Sa: {
      index: 29,
      name: "Sa",
      fontpic:require('../../assets/img/letter/30.png'),
      pic:require('../../assets/img/fontCharacters/sarpo.png'),
      uril:require('../../assets/sounds/words/Sa.m4a'),
      isVideo:false,
    },
    Sha: {
      index: 30,
      name: "Sha",
      fontpic:require('../../assets/img/letter/31.png'),
      pic:require('../../assets/img/fontCharacters/sankha.png'),
      uril:require('../../assets/sounds/words/Sa.m4a'),
      isVideo:false,
    },
    Ssa: {
      index: 31,
      name: "Ssa",
      fontpic:require('../../assets/img/letter/32.png'),
      pic:require('../../assets/img/fontCharacters/sadkod.png'),
      uril:require('../../assets/sounds/words/Sa.m4a'),
      isVideo:false,
    },
    Ha: {
      index: 32,
      name: "Ha",
      fontpic:require('../../assets/img/letter/33.png'),
      pic:require('../../assets/img/fontCharacters/halo.png'),
      uril:require('../../assets/sounds/words/Ha.m4a'),
      isVideo:false,
    },
    Xya: {
      index: 33,
      name: "Xya",
      fontpic:require('../../assets/img/letter/34.png'),
      pic:require('../../assets/img/fontCharacters/warrior.png'),
      uril:require('../../assets/sounds/words/Xya.m4a'),
      isVideo:false,
    },
    Tra: {
      index: 34,
      name: "Tra",
      fontpic:require('../../assets/img/letter/35.png'),
      pic:require('../../assets/img/fontCharacters/trisul.png'),
      uril:require('../../assets/sounds/words/Tra.m4a'),
      isVideo:false,
    },
    Gya: {
      index: 35,
      name: "Gya",
      fontpic:require('../../assets/img/letter/36.png'),
      pic:require('../../assets/img/fontCharacters/gyani.png'),
      uril:require('../../assets/sounds/words/Gya.m4a'),
      isVideo:false,
    },
}